<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DILG Monthly Incident Report - {{ $month->format('F Y') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            line-height: 1.4;
            color: #1a1a1a;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #1e3a5f;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }
        .header h1 {
            font-size: 14px;
            margin: 0;
            color: #1e3a5f;
        }
        .header h2 {
            font-size: 12px;
            margin: 2px 0 0;
            color: #555;
            font-weight: normal;
        }
        .header .report-title {
            font-size: 16px;
            font-weight: bold;
            margin-top: 8px;
            color: #1e3a5f;
        }
        .header .report-period {
            font-size: 13px;
            margin-top: 4px;
            color: #333;
        }
        .section {
            margin-bottom: 14px;
        }
        .section-title {
            font-size: 12px;
            font-weight: bold;
            color: #1e3a5f;
            border-bottom: 1px solid #ccc;
            padding-bottom: 3px;
            margin-bottom: 6px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 8px;
        }
        table td, table th {
            padding: 4px 8px;
            border: 1px solid #ddd;
            font-size: 10px;
        }
        table th {
            background-color: #f0f4f8;
            text-align: left;
            font-weight: bold;
        }
        .total-highlight {
            font-size: 14px;
            font-weight: bold;
            color: #1e3a5f;
            margin-bottom: 8px;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #888;
            border-top: 1px solid #ccc;
            padding-top: 8px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>CITY DISASTER RISK REDUCTION AND MANAGEMENT OFFICE</h1>
        <h2>BUTUAN CITY</h2>
        <div class="report-title">DILG Monthly Incident Report</div>
        <div class="report-period">{{ $month->format('F Y') }}</div>
    </div>

    <div class="section">
        <div class="section-title">Summary</div>
        <div class="total-highlight">Total Incidents: {{ $total }}</div>
        <table>
            <tr>
                <th>Priority</th>
                <th>Count</th>
            </tr>
            @foreach ($byPriority as $priority => $count)
                <tr>
                    <td>{{ $priority }}</td>
                    <td>{{ $count }}</td>
                </tr>
            @endforeach
        </table>
    </div>

    <div class="section">
        <div class="section-title">Breakdown by Incident Type</div>
        <table>
            <tr>
                <th>Type</th>
                <th>Count</th>
                <th>%</th>
            </tr>
            @foreach ($byType as $type => $count)
                <tr>
                    <td>{{ $type }}</td>
                    <td>{{ $count }}</td>
                    <td>{{ $total > 0 ? number_format(($count / $total) * 100, 1) : '0.0' }}%</td>
                </tr>
            @endforeach
        </table>
    </div>

    <div class="section">
        <div class="section-title">Top Barangays by Incident Count</div>
        <table>
            <tr>
                <th>Barangay</th>
                <th>Count</th>
                <th>%</th>
            </tr>
            @foreach ($byBarangay as $barangay => $count)
                <tr>
                    <td>{{ $barangay }}</td>
                    <td>{{ $count }}</td>
                    <td>{{ $total > 0 ? number_format(($count / $total) * 100, 1) : '0.0' }}%</td>
                </tr>
            @endforeach
        </table>
    </div>

    <div class="section">
        <div class="section-title">Breakdown by Outcome</div>
        <table>
            <tr>
                <th>Outcome</th>
                <th>Count</th>
                <th>%</th>
            </tr>
            @foreach ($byOutcome as $outcome => $count)
                <tr>
                    <td>{{ str_replace('_', ' ', ucfirst($outcome)) }}</td>
                    <td>{{ $count }}</td>
                    <td>{{ $total > 0 ? number_format(($count / $total) * 100, 1) : '0.0' }}%</td>
                </tr>
            @endforeach
        </table>
    </div>

    <div class="footer">
        Generated by IRMS on {{ now()->format('Y-m-d H:i:s') }} | CDRRMO Butuan City
    </div>
</body>
</html>
