<?php

namespace App\Http\Controllers;

use App\Enums\FrasAccessAction;
use App\Enums\FrasAccessSubject;
use App\Enums\UserRole;
use App\Models\FrasAccessLog;
use App\Models\RecognitionEvent;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

final class FrasEventFaceController extends Controller
{
    /**
     * Stream the face image crop for a RecognitionEvent.
     *
     * Access-controlled by a temporarySignedRoute URL (5-min TTL, generated by
     * IntakeStationController::show() per D-18 and ResponderController via the
     * PersonOfInterestHydrator) AND by role gate. Operators, supervisors,
     * admins, and responders may fetch — responders need the face to identify
     * a Person-of-Interest on scene (CDRRMO operational override of the
     * original D-27 exclusion). Scene imagery is still denied to responders
     * by FrasEventSceneController per D-26.
     *
     * Every successful fetch (including responder views) appends a
     * fras_access_log row inside a DB::transaction BEFORE the stream is
     * returned — any DB error throws out of the transaction and the stream
     * never reaches the caller. This preserves the DPA audit trail.
     */
    public function show(Request $request, RecognitionEvent $event): StreamedResponse
    {
        $user = $request->user();
        $allowedRoles = [
            UserRole::Operator,
            UserRole::Supervisor,
            UserRole::Admin,
            UserRole::Responder,
        ];

        abort_unless($user && in_array($user->role, $allowedRoles, true), 403);
        abort_unless($event->face_image_path, 404);

        // Phase 19/20 convention: face crops stored on the 'fras_events' private disk.
        $disk = Storage::disk('fras_events');
        abort_unless($disk->exists($event->face_image_path), 404);

        DB::transaction(function () use ($request, $user, $event) {
            FrasAccessLog::create([
                'actor_user_id' => $user->id,
                'ip_address' => $request->ip(),
                'user_agent' => substr((string) $request->userAgent(), 0, 255),
                'subject_type' => FrasAccessSubject::RecognitionEventFace->value,
                'subject_id' => $event->id,
                'action' => FrasAccessAction::View->value,
                'accessed_at' => now(),
            ]);
        });

        return $disk->response($event->face_image_path, basename($event->face_image_path), [
            'Content-Type' => 'image/jpeg',
            'X-Content-Type-Options' => 'nosniff',
            'Cache-Control' => 'private, no-store, max-age=0',
        ]);
    }
}
